### ISSUE TITLE
Can't establish web socket 

### ISSUE THREAD

**Issue by xldenis** [sdroege/async-tungstenite#10]
The latest release (0.4.0) seems to error when you attempt to create a websocket

You can reproduce using: 
```
use async_std::task;
use async_std::net::{TcpListener, TcpStream, SocketAddr};

fn main () {
    task::block_on(server());
}
async fn server() {
    let server = TcpListener::bind("127.0.0.1:3012").await.unwrap();
    while let Ok((stream, addr)) = server.accept().await {
        task::spawn(handle_connection(stream, addr));
    }
}

async fn handle_connection(raw_stream: TcpStream, _addr: SocketAddr) {
    println!("{:?}", _addr);
    async_tungstenite::accept_async(raw_stream).await.unwrap();
}
```

Then create a websocket using `new WebSocket("ws://localhost:3012")`.

Weirdly enough, it's still possible to create a websocket connection using `websocat`

**Comment by sdroege** [comment]
Can you provide a full testcase for the client? Also which browser or Javascript implementation are you using?

What would also help is a wireshark/tcpdump capture of the communication with 0.4 and the previous version that worked.

Thanks for reporting :)

**Comment by xldenis** [comment]
> Can you provide a full testcase for the client? Also which browser or Javascript implementation are you using?

That was the full command, on latest Firefox

As for the backend dependencies my `Cargo.toml` was

```
[dependencies]
async-tungstenite = "0.4.0"
async-std = "*"
```

**Comment by sdroege** [comment]
That's a bug in tungstenite and fixed there in git already: https://github.com/snapview/tungstenite-rs/pull/106

**Comment by xldenis** [comment]
thanks! I'll wait for the next release then :)
