### ISSUE TITLE
How to close connection gracefully after WebSocketStream.split()?

### ISSUE THREAD

**Issue by PieceOfGood** [sdroege/async-tungstenite#109]
For a simple situation, the `close()` method needs to pass `CloseFrame`:
```rust
let close_frame = CloseFrame {code: CloseCode::Normal, reason: Cow::from("")};
ws_stream.close(close_frame).await;
```
But if I call [split()](https://docs.rs/futures-util/0.3.21/futures_util/stream/trait.StreamExt.html#method.split) for `ws_stream` to create tasks with their participation, method `close()` stops taking arguments, what throws an exception on the echo server side, like this:
`websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])`
The server continues to run, but in its console it is always an exception when the connection is terminated in the last way.

**Comment by sdroege** [comment]
You can pass a `Message::Close` through the `Sink` part. If you look at the code of [`WebSocketStream::close`](https://docs.rs/async-tungstenite/latest/src/async_tungstenite/lib.rs.html#298-304), that's literally what it does :)

[`Sink::close`](https://docs.rs/futures/latest/futures/sink/trait.SinkExt.html#method.close) comes from `SinkExt` and just closes the connection directly.

Does that help?

**Comment by PieceOfGood** [comment]
Yes, that's what I need.
Thanks a lot!
