### ISSUE TITLE
How to fetch GET params on server?

### ISSUE THREAD

**Issue by Earthson** [sdroege/async-tungstenite#11]
For urls like like `ws://localhost:8080/?a=3`, how could we get `a=3` on the server?

**Comment by sdroege** [comment]
You could use the `accept_hdr*` functions, which give you a callback where you can look at the HTTP `Request`.

I think it would make sense for tungstenite itself to provide the `Request` together with the websocket as return value though, which then would also allow us to have it easily in the async variant. That would have to be done in tungstenite first.

**Comment by Earthson** [comment]
it works:) thx
