### ISSUE TITLE
[Question]: How to optimise the memory usage for websocket client

### ISSUE THREAD

**Issue by coder3101** [sdroege/async-tungstenite#111]
Hi,
I am writing a load testing tool and my use case demand opening up many websocket connections to a server, each connection is long lived and has a keep-alive send and receive mechanism, where every client sends "keep-alive" (text message) at interval of 4 second. Server also sends keep-alive text and some events as they occur.

Running that load tool on a k8 pod with 4G of memory limit results in OOM after opening up 5000 connections. I suspect the memory usage shoots up because of websocket connections as I tried to run without opening connection and memory usage was well under 500M.
  
I was wondering if there is a way to reduce the memory usage of client since I would like to open as many connections as possible with limited resource without triggering OOM. 

I am using tokio-runtime with this library, I tried various different libraries such as:
- [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite)
- [websocket_lite](https://github.com/1tgr/rust-websocket-lite)

I did not find any difference significant difference.

Thanks

**Comment by sdroege** [comment]
Use a profiler and check where the memory is actually used up, and then we can look at optimizing those things :)
Do you have a testcase for this that you can share btw?

**Comment by coder3101** [comment]
I profiled using instruments and found that `native-tls` on linux was causing too much memory allocation. I replaced it with `rust-tls` and now 10 times less memory is being allocated. 

During profiling I also found that `connect_async` was the highest contributor to memory usage.

**Comment by sdroege** [comment]
> During profiling I also found that `connect_async` was the highest contributor to memory usage.

Which part?

**Comment by coder3101** [comment]
For native-tls, `connect_async` handshake is consuming most, also for some reason this is more prevalent incase of linux.

![Screenshot 2022-12-23 at 7 34 22 PM](https://user-images.githubusercontent.com/22212259/209348767-49d9ea72-52ba-4421-ba8a-fe580a3da040.png)

For rustls-tls

![Screenshot 2022-12-23 at 7 36 26 PM](https://user-images.githubusercontent.com/22212259/209348909-017bdbc5-3aab-42a0-a2fd-7ef72f362d56.png)

**Comment by sdroege** [comment]
I see. Do you see any possibility of optimization in there? :)
