### ISSUE TITLE
could not find `async_std` in `async_tungstenite`

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [sdroege/async-tungstenite#112]
-

**Comment by sdroege** [comment]
How can this be reproduced?

**Comment by Proxtx** [comment]
its used in the example client

**Comment by Proxtx** [comment]
this can be fixed by enabeling the "async-std-runtime" feature

**Comment by sdroege** [comment]
Should be added to the `required-features` then indeed :) Do you want to make a PR?

**Comment by Proxtx** [comment]
It's already there but @hp8wvvvgnj6asjm7 didn't use the appropriate cargo function to run the example.

**Comment by sdroege** [comment]
Ah that's what you mean. Let's close this then I guess?
