### ISSUE TITLE
Provide a simple `async fn send` method for better interoperability with `futures-lite` based facilities

### ISSUE THREAD

**Issue by stackinspector** [sdroege/async-tungstenite#142]
[Smol(`futures-lite`)'s guys think that `futures_sink::Sink` (till v0.3) is a legacy API and excluded related APIs in `futures-lite` intentionally. They prefer a simple `async fn send` API.](https://github.com/smol-rs/futures-lite/blob/5a355ae46a73c38a9a9b60c0940e983a325d799c/FEATURES.md#sink-trait)
Before a new simple `Sink` API is normalized, I suggest considering implementing a simple `async fn send` method:
```rust
impl<S> WebSocketStream<S> {
    /// Simple send method to replace `futures_sink::Sink` (till v0.3).
    pub async fn send(&mut self, msg: Message) -> Result<(), WsError>
    where
        S: AsyncRead + AsyncWrite + Unpin,
    {
        // Example to make it work. A simpler internal way can be used to implement it.
        SinkExt::send(self, msg).await
    }
}
```
In an ideal world, the `send` method would be called even if the `SinkExt` was introduced. I'm not sure if there would be additional problems if a method name is duplicated with a method in trait.
cc smol-rs/futures-lite#111 smol-rs/futures-lite#112

**Comment by stackinspector** [comment]
smol/futures-lite#112 has been merged.
Final document: https://github.com/smol-rs/futures-lite/blob/master/FEATURES.md

**Comment by sdroege** [comment]
I'm also not a fan of the `Sink` API. Having a simple `send()` function like this would seem like a good idea. Do you want to provide a PR for adding it?

**Comment by stackinspector** [comment]
I tried but I realized I'm not very good at handling details of async primitives. Considering code robustness, it might be a good idea to assign community members who's more experienced.
