### ISSUE TITLE
If tokio-runtime feature is enabled, implement tokio AsyncRead/Write traits on WebSocket and provide a From impl for the adapter

### ISSUE THREAD

**Issue by sdroege** [sdroege/async-tungstenite#28]

**Comment by najamelan** [comment]
[ws_stream_tungstenite](https://docs.rs/ws_stream_tungstenite) provides this if you want to spare the work.

**Comment by sdroege** [comment]
> [ws_stream_tungstenite](https://docs.rs/ws_stream_tungstenite) provides this if you want to spare the work.

Not really? That does something completely different :)

But also this issue makes no sense. `WebSocket` is a `Stream`/`Sink`, and for that tokio fortunately does not provide its own traits.
