### ISSUE TITLE
Where does the split() method come from?

### ISSUE THREAD

**Issue by S1nus** [sdroege/async-tungstenite#29]
Forgive me if this is a bad place to ask, but I cannot find where the `async_tungstenite::WebSocketStream` object inherits the `.split()` method from

it's used on line 40 of the `echo-server.rs` example

**Comment by sdroege** [comment]
From the `futures` crate: [`StreamExt::split()`](https://docs.rs/futures/0.3.5/futures/stream/trait.StreamExt.html#method.split)
