### ISSUE TITLE
Type aliases for `WebSocketStream` would be useful.

### ISSUE THREAD

**Issue by d4h0** [sdroege/async-tungstenite#35]
Hi,

I have to store the WebSocket that's returned by [`async_tungstenite::tokio::connect_async`](https://docs.rs/async-tungstenite/0.6.0/async_tungstenite/tokio/fn.connect_async.html) in a struct without adding a type parameter to it.

The return value of the above function is `Result<(WebSocketStream<StreamSwitcher<TokioAdapter<TcpStream>, TokioAdapter<TlsStream<TokioAdapter<TokioAdapter<TcpStream>>>>>>, Response), Error>`.

So a WebSocket is represented by:

`WebSocketStream<StreamSwitcher<TokioAdapter<TcpStream>, TokioAdapter<TlsStream<TokioAdapter<TokioAdapter<TcpStream>>>>>>`

Which is pretty complex.

I tried to construct my own type alias, but I failed because I don't have a TLS feature activated, so I can't rebuild the type.

I guess, the problem is connected to the use of certain features and the limitations of `cargo doc` but at that point, I gave up and switched to `tokio-tungstenite` (which doesn't seem to have this problem).

I think type aliases would be very useful here (or at least examples that show how to store a WebSocket somewhere).

PS: I'm pretty new to Rust, so sorry if the right way to do this is obvious.

**Comment by sdroege** [comment]
The return type of `connect_async` should be `WebSocketStream<AutoStream<TokioAdapter<TcpStream>>>`, not sure why rustdoc doesn't show that correctly.

How is this simpler in `tokio-tungstenite`, should be more or less the same type apart from the `TokioAdapter` or not?

**Comment by d4h0** [comment]
> not sure why rustdoc doesn't show that correctly.

The problem seems to be that at least `AutoStream` is private to the crate. See line [93](https://docs.rs/async-tungstenite/0.6.0/src/async_tungstenite/tokio.rs.html#93) and [103](https://docs.rs/async-tungstenite/0.6.0/src/async_tungstenite/tokio.rs.html#103) of `async_tungstenite/tokio.rs`.

In `tokio-tungstenite` it seems to be `WebSocketStream<TcpStream>`.

**Comment by sdroege** [comment]
In any case, having *public* type aliases for these things would be good :) Do you want to provide a PR for that?

**Comment by d4h0** [comment]
To be honest, I don't even know how I would create the type aliases. When I tried before, I failed (as I wrote, I'm pretty new to Rust :)).

**Comment by sdroege** [comment]
Ok, I'll add something :)

**Comment by sdroege** [comment]
This is done now and part of the 0.7.0 release. I've also made things generally simpler for tokio users.

Maybe you want to give it a try again and let me know if there's something else confusing/difficult for you? Thanks!

**Comment by d4h0** [comment]
Awesome! :)

At the moment I'm refactoring/extending my code and it doesn't compile. After it compiles again, I will give `async-tungstenite` again a try.
