### ISSUE TITLE
Integrating openssl support?

### ISSUE THREAD

**Issue by jdm** [sdroege/async-tungstenite#39]
From a brief glance, it appears that TLS support in async-tungstenite requires intentional, custom integration for each TLS crate. Servo is considering switching to tungstenite in https://github.com/servo/servo/issues/27043; would a PR for openssl support in this crate be desirable?

**Comment by sdroege** [comment]
Sure, `async-tungstenite` already support 3 different TLS implementations so why not a 4th :)

Ideally this would make use of an existing async/tokio OpenSSL wrapper though, it seems like such a thing should already exist and if it doesn't it would make sense to exist as a separate crate.
