### ISSUE TITLE
Disable certificate verification

### ISSUE THREAD

**Issue by importcjj** [sdroege/async-tungstenite#4]
Nice crate!  But I just need your help.

There was a server with which the client failed to verify the certificate when I established a TLS connection.

The following is the error message: 

`tungstenite error IO error: invalid certificate: UnknownIssuer`

Is there any way to disable certificate verification.

**Comment by importcjj** [comment]
There are some resources may helped.

## rustls

It has a `dangerous_configuration ` feature allow the user to disable certificate verification.

See the example https://github.com/ctz/rustls/blob/master/rustls-mio/examples/tlsclient.rs#L446

## native-tls
TlsConnectorBuilder has a function `danger_accept_invalid_certs` to do this.

https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsConnectorBuilder.html#method.danger_accept_invalid_certs

**Comment by importcjj** [comment]
## Example
```toml
async-tungstenite = "0.2.1"
async-tls = "0.6"
rustls = { version = "0.16", features=["dangerous_configuration"]}
webpki = "0.21.0"
```

```rust
use async_std::net::TcpStream;
use async_tungstenite::{MaybeTlsStream, WebSocketStream};
use tungstenite::handshake::client::{Request, Response};

pub async fn connect_tls_disable_cert_verification<R>(
    req: R,
) -> std::result::Result<(WebSocketStream<MaybeTlsStream<TcpStream>>, Response), tungstenite::Error>
where
    R: Into<Request<'static>> + Unpin,
{
    use async_tls::TlsConnector;
    use rustls::ClientConfig;
    use std::sync::Arc;

    mod danger {
        use webpki;

        pub struct NoCertificateVerification {}

        impl rustls::ServerCertVerifier for NoCertificateVerification {
            fn verify_server_cert(
                &self,
                _roots: &rustls::RootCertStore,
                _presented_certs: &[rustls::Certificate],
                _dns_name: webpki::DNSNameRef<'_>,
                _ocsp: &[u8],
            ) -> Result<rustls::ServerCertVerified, rustls::TLSError> {
                Ok(rustls::ServerCertVerified::assertion())
            }
        }
    }


    let request: Request = req.into();
    let mut config = ClientConfig::new();
    config
        .dangerous()
        .set_certificate_verifier(Arc::new(danger::NoCertificateVerification {}));
    let connector = TlsConnector::from(Arc::new(config));

    async_tungstenite::connect_async_with_tls_connector(request, Some(connector)).await
}

```

**Comment by sdroege** [comment]
There's also `connect_async_with_tls_connector()` that you could use here. Saves you some more lines :)

**Comment by importcjj** [comment]
Aha, thanks for the tip  :)

**Comment by araa47** [comment]
Hi, I am currently trying to solve the same issue and have had no luck in getting a working version connected. I need to disable ssl verification. Can anyone please help or guide me in the right direction?

Error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "tls handshake eof" })', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by sdroege** [comment]
@araa47 Which configuration (async runtime and TLS library) are you using? Where exactly does that `unwrap()` come from (`RUST_BACKTRACE=1` will tell you)?

Maybe you can provide a minimal testcase for reproducing this problem, that would make it easier to debug it.

**Comment by araa47** [comment]
I'm unable to share the private ws url with the self signed certificate, but I can share the code snippet.

*RUST_BACKTRACE=1*
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: UnexpectedEof, error: "tls handshake eof" })', src/libcore/result.rs:1165:5

```

Based on the python implementation it seems to be a problem with verifying the self signed certificate, so in the python module, ssl is disabled while connecting to this websocket, eventhough the url starts with wss. 

```
use tokio;
use async_tungstenite::{tokio::{connect_async}};
use futures::prelude::*;
use tungstenite::protocol::Message;
use serde_json::json;

// Base url for ws
const WS_BASE_URL: &'static str = "wss://custom-url";
// function that subscribes to data
async fn subscribe() {
    // build the ws url connection request add tls support for wss
    #[cfg(not(any(feature = "tokio-tls", feature = "tokio-runtime")))]
        let url = url::Url::parse(WS_BASE_URL).unwrap();
    // connect to the ws
    let (mut ws_stream, _) = connect_async(url.clone()).await.unwrap();
    let parsed = json!({
                    "event": "subscribe",
                  });
    let text = parsed.to_string();
    ws_stream.send(Message::text(text)).await.unwrap();

    // while connected
    loop {
        // wait for messages
        let msg = ws_stream
            .next()
            .await
            .ok_or_else(|| "didn't receive anything").unwrap().unwrap();

        match msg{
            Message::Text(msgtxt)=> {println!("{:?}", msgtxt)
            },
            Message::Ping(_msg) => continue,
            Message::Binary(_msg)=> continue,
            Message::Pong(_msg)=> continue,
            Message::Close(msg)=> {println!("Close {:?}", msg); // re-open connection here
                let (mut ws_stream, _) = connect_async(url.clone()).await.unwrap();
            },
        };
    }
}
#[tokio::main]
async fn main(){
    subscribe().await;
}
```

**Comment by krzysztofgal** [comment]
I am not sure about this particular ssl impl. But when You want to use self signed certs - You must "validate" it on client machine, either by adding rootCA to system config or maybe by tls config in Your code, otherwise Your cert will be seen by clients as invalid.

**Comment by Darkspirit** [comment]
Please use https://github.com/FiloSottile/mkcert or XCA instead of a self-signed certificate.

**Comment by araa47** [comment]
The problem is I also don't have access to the server code. So I'm currently basing my rust implementation of the old python implementation.

**Comment by sdroege** [comment]
> _RUST_BACKTRACE=1_

This should give you a proper backtrace so we can know which `unwrap()` is actually triggering there. I assume it's the one in `connect_async()` in your code.

What you want is `connect_async_with_tls_connector()` so that you can pass in your custom TLS connector with a configuration that accepts your certificate. You probably want to make use of [this](https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsConnectorBuilder.html#method.danger_accept_invalid_certs) when building it.

**Comment by martin00001313** [comment]
Also please note that for your 'NoCertificateVerification you need to implement 'verify_tls12-signature' and 'verify_tls13_signature'(otherwice you'll get BadDER error). So the final version would be 



`impl rustls::ServerCertVerifier for NoCertificateVerification {
    fn verify_server_cert(
        &self,
        _roots: &rustls::RootCertStore,
        _presented_certs: &[rustls::Certificate],
        _dns_name: webpki::DNSNameRef,
        _ocsp_response: &[u8],
    ) -> Result<rustls::ServerCertVerified, rustls::TLSError> {
        Ok(rustls::ServerCertVerified::assertion())
    }

    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &rustls::Certificate,
        _dss: &rustls::internal::msgs::handshake::DigitallySignedStruct,
    ) -> Result<rustls::HandshakeSignatureValid, rustls::TLSError> {
        Ok(rustls::HandshakeSignatureValid::assertion())
    }

    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &rustls::Certificate,
        _dss: &rustls::internal::msgs::handshake::DigitallySignedStruct,
    ) -> Result<rustls::HandshakeSignatureValid, rustls::TLSError> {
        Ok(rustls::HandshakeSignatureValid::assertion())
    }
}`
