### ISSUE TITLE
Cannot send customized message in example "server"

### ISSUE THREAD

**Issue by Riemannstein** [sdroege/async-tungstenite#47]
I am trying to change server.rs so that a customized message is sent instead of a clone of a received one.

Line 75 in "examples/server.rs" changed to 
``for recp in broadcast_recipients {
               // recp.unbounded_send(msg.clone()).unwrap();
                recp.unbounded_send(Message::text("abc".to_string())).unwrap();
  }``

But when I open 2 client connections and send messages from one connection, nothing is received on the other connection.

Appreciate it if some help is provided.

**Comment by sdroege** [comment]
Can you provide a runnable, minimal example for showing the problem you're running into?

**Comment by Riemannstein** [comment]
> Can you provide a runnable, minimal example for showing the problem you're running into?

I am not sure if the following informration is enough. But be sure to let me if additional info is needed.

I attached server.rs (modified based on the project example with the only change described in the issue above) and client.rs (identical to the project example).

I first start the server by running the following command:

`cargo run --features="async-std-runtime" --example server 127.0.0.1:12345`

The server can start normally:

![image](https://user-images.githubusercontent.com/22661421/91182304-9568df00-e71c-11ea-81d0-aba7b0608547.png)

I start two clients by running:

`cargo run --features="async-std-runtime" --example client ws://127.0.0.1:12345/`

Both clients start normally (only showing one screenshot because both are identical)

![image](https://user-images.githubusercontent.com/22661421/91182659-060ffb80-e71d-11ea-8785-bcd4cdff3d7e.png)

When I send message from one client ("Hello"), the server can receive the message:

![image](https://user-images.githubusercontent.com/22661421/91182810-3d7ea800-e71d-11ea-9a37-d822cef19350.png)

But the other client does not recieve anything:

![image](https://user-images.githubusercontent.com/22661421/91183142-b0881e80-e71d-11ea-911e-6a82c6bfe790.png)

Based on my understanding, with the changes I made, the other client should receive "abc" instead of nothing. 

The is the problem I need help with. 

Thanks in advance for your time.

[example.zip](https://github.com/sdroege/async-tungstenite/files/5124037/example.zip)

**Comment by sdroege** [comment]
Thanks, I'll try to take a look in the next days :)

**Comment by sdroege** [comment]
Probably because your `stdout` is line buffered. If you change the client to

```rust
        read.for_each(|message| async {
            let data = message.unwrap().into_data();
            async_std::io::stdout().write_all(&data).await.unwrap();
            async_std::io::stdout().write_all(b"\n").await.unwrap();
        })
```

it will work fine. The existing example works because there's a newline at the end of each message (from pressing enter in the other client).

Similarly if using the [`println!`](https://docs.rs/async-std/1.6.3/async_std/macro.println.html) macro from async-std or std.

**Comment by Riemannstein** [comment]
> Probably because your `stdout` is line buffered. If you change the client to
> 
> ```rust
>         read.for_each(|message| async {
>             let data = message.unwrap().into_data();
>             async_std::io::stdout().write_all(&data).await.unwrap();
>             async_std::io::stdout().write_all(b"\n").await.unwrap();
>         })
> ```
> 
> it will work fine. The existing example works because there's a newline at the end of each message (from pressing enter in the other client).
> 
> Similarly if using the [`println!`](https://docs.rs/async-std/1.6.3/async_std/macro.println.html) macro from async-std or std.

Indeed it works. Big thanks!
