### ISSUE TITLE
AsyncRead / AsyncWrite for WebsocketStream?

### ISSUE THREAD

**Issue by black-binary** [sdroege/async-tungstenite#62]
AsyncRead/AsyncWrite traits didn't implement for WebSocketStream. Is there any plan for this?

**Comment by sdroege** [comment]
WebSockets are a message-based protocol, that's why `WebSocketStream` implements `Stream` and `Sink` around a message type.

There's however a crate implementing `AsyncRead`/`AsyncWrite`: https://crates.io/crates/ws_stream_tungstenite
