### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by RAnders00** [sdroege/async-tungstenite#66]
When upgrading to a new version it would be nice to know what changed. I'm suggesting that for future releases a changelog is kept in a file like `CHANGELOG.md` or similar.

**Comment by sdroege** [comment]
Good idea, and I usually do that for my crates. Just didn't do that here because it started as a fork of tokio-tungstenite :)

Do you want to send a PR that adds a changelog like https://github.com/sdroege/sdp-types/blob/master/CHANGELOG.md and adds at least a few of the previous releases?
