### ISSUE TITLE
[Question] What's the best practice to implement a simple websocket client with this crate?

### ISSUE THREAD

**Issue by aurexav** [sdroege/async-tungstenite#69]
I'm sorry to open an issue here. Maybe could you turn on the Github discussion feature on this repo?

Is this a good way to handle read&write (with `match select(...)`)? https://github.com/l2ust/substrater/blob/main/src/websocket.rs#L58-L110

And how do I know if a connection is lost? 
For example, if the connection lost this will cause a deadlock. What kind of check should I do within this function? https://github.com/l2ust/substrater/blob/main/src/websocket.rs#L317
My poor idea is to make a `read()` one more time to check the connection state.

**Comment by sdroege** [comment]
> Is this a good way to handle read&write

Maybe you're looking for https://docs.rs/futures/0.3.8/futures/stream/trait.StreamExt.html#method.split to be able to split the `Stream` and `Sink` parts into separate variables that can be used independently?

> And how do I know if a connection is lost?

What do you mean with lost exactly? The connection was closed? Then reading from the `Stream` should return `None`, writing to the `Sink` should give an `UnexpectedEof` error.
