### ISSUE TITLE
could not find `async_std` in `async_tungstenite`

### ISSUE THREAD

**Issue by araa47** [sdroege/async-tungstenite#7]
Hi I'm trying to install async-tungstentine and use it in my project. 

I stated by adding the following to my Cargo.toml
```
async-tungstenite = "*"
futures = "*"
```
then i tried copying over the examples/async-std-echo.rs to my main.rs and running, however I get the following error.
```
error[E0432]: unresolved import `async_tungstenite::async_std`
  --> src/main.rs:15:25
   |
15 | use async_tungstenite::{async_std::connect_async, tungstenite::Message};
   |                         ^^^^^^^^^ could not find `async_std` in `async_tungstenite`

error[E0432]: unresolved import `async_std`
  --> src/main.rs:18:5
   |
18 | use async_std::task;
   |     ^^^^^^^^^ use of undeclared type or module `async_std`

warning: unused import: `futures::prelude`

```
Do i have to enable some features in my Cargo.toml to use this?

**Comment by krzysztofgal** [comment]
Yes.
[https://docs.rs/async-tungstenite/0.3.1/async_tungstenite/](https://docs.rs/async-tungstenite/0.3.1/async_tungstenite/)

**Comment by aveao** [comment]
Including a link to those on README.md would be a good idea.

**Comment by sdroege** [comment]
There's a link to the docs in the `README.md` and the second section mentions the part about the feature flags. Can you suggest a way how to make this more obvious, maybe with a PR to change it accordingly?

**Comment by PieceOfGood** [comment]
Exactly the same problem.
The link above doesn't explain anything.
Please tell me if there is anything else I need to do to use it besides:
```
[dependencies]
async-tungstenite = "*"
```
?

**Comment by sdroege** [comment]
You need to enable the `async-std-runtime` cargo feature for getting `async-std` support. See the list at https://github.com/sdroege/async-tungstenite#what-is-async-tungstenite for more details.

Do you have suggestions how to make this more obvious?

**Comment by PieceOfGood** [comment]
Above (or below) this list, write the same example as in the example with dependencies, which will indicate the section and what needs to be added to it. For example:
```
[features]
default = ["async-std-runtime"]
async-std-runtime = ["async-std", "async-tungstenite/async-std-runtime"]
```
Peeped [here](https://github.com/mattsse/chromiumoxide/blob/main/Cargo.toml).
But it doesn't work.

**Comment by sdroege** [comment]
Can you give a full example that doesn't work for you?

**Comment by PieceOfGood** [comment]
This worked:
```
[features]
default = ["async-std-runtime"]
async-std-runtime = ["async-tungstenite/async-std-runtime"]
```
But, the [echo](https://github.com/sdroege/async-tungstenite/blob/master/examples/async-std-echo.rs) example fails on connection:
`Err(Http(Response { status: 200, version: HTTP/1.1, headers: {"x-amz-id-2": "w6IM8TOcdq894Xx+f1Ecis9/tVZ3k2hLY765z9W0oFvA4TYKLv9dylOP2D0itDGyaHI6kpwGzh4=", "x-amz-request-id": "VYWZNTCSS9A77Q1C", "date": "Wed, 07 Sep 2022 11:44:27 GMT", "last-modified": "Thu, 26 Aug 2021 03:35:42 GMT", "etag": "\"6d5a28f4c5e297e95a29988884c9e896\"", "content-type": "text/html", "server": "AmazonS3", "content-length": "4413", "connection": "close"}, body: None }))`

**Comment by sdroege** [comment]
The server apparently replies with HTML instead of the websocket protocol upgrade. Can you create an issue for that?

**Comment by PieceOfGood** [comment]
Apparently, this is due to the fact that it no longer works.
echo.websocket.org
This service is no longer available.

**Comment by sdroege** [comment]
Indeed. If you know an alternative we can switch to that here :)
