### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by araa47** [sdroege/async-tungstenite#8]
Hi I am trying to compare tungstenite with async_tungstenite to see if their is a huge performance difference between connecting to multiple websockets using multiple threads in tungstenite vs using tokio spawn in async_tungstenite.

I would have expected their to be a huge difference (I come from python and in python these implementations have a huge performance difference), but what I notice is the async implementation seems to use less threads, but more cpu usage. Is this expected? Or am i using the library incorrectly by spawning the async futures in the wrong way? I cant seem to get my async implementation to run faster than the sync.

In my example i connect to the binance market data websockets to compare the performance on my machine. I run ```cargo build --release``` and run the target/release/myproject file to compare on my mac. Ive attached code snippets below. 

*Sync Implementation*
```
use tungstenite::{connect, WebSocket};  
use url::Url;  
use std::{thread, time};  
use tungstenite::handshake::client::Response;  
use tungstenite::protocol::Message;  
use tungstenite::client::AutoStream;  
  
  
const WS_BASE_URL: &'static str = "wss://stream.binance.com:9443";  
  
 
fn connect_to_markets(url: &String) -> WebSocket<AutoStream>{  
    let (socket, response) = connect(Url::parse(url).unwrap()).expect("Cant Connect");  
  socket  
}  
  
fn subscribe_to_market(pair: &'static str){  
    let ws_url = format!("{}/ws/{}@depth20", WS_BASE_URL, pair);  
  println!("{}", &ws_url);  
  let mut socket = connect_to_markets(&ws_url);  
  loop{  
        let msg = socket.read_message().expect("Error reading message");  
  match msg{  
            Message::Text(msgtxt)=> {  
                                       println!("Message {:?}", msgtxt)    
                                            },  
  Message::Ping(_msg) => continue,  
  Message::Binary(_msg)=> continue,  
  Message::Pong(_msg)=> continue,  
  Message::Close(msg)=> {println!("Close {:?}", msg); // re-open connection here  
  let mut socket = connect_to_markets(&ws_url);  
  },  
  };  
  }  
}  
  
fn main() {  
    let markets = vec!["btcusdt", "ethusdt", "etcusdt", "bchusdt","bnbusdt", "eosusdt","xrpusdt" ,"ltcusdt","busdusdt","zecusdt","adausdt", "btcpax","atomusdt", "trxusdt", "xlmusdt", "bttusdt", "vetusdt", "tusdusdt"];  
  let mut children = vec![];  
  for pair in markets{  
        children.push(thread::spawn(move||{  
            println!("Market started for {}", pair);  
  subscribe_to_market(pair);  
  }))  
    }  
    for child in children{  
        let _ = child.join();  
  }  
}
```

*Async Implementation*
```
use tokio;  
use async_tungstenite::{tokio::connect_async};  
use futures::prelude::*;  
use tungstenite::protocol::Message;  
  

  
// Base url for ws  
const WS_BASE_URL: &'static str = "wss://stream.binance.com:9443";  
  
// function that subscribes to markets and currently just prints out the ob  
async fn subscribe_to_market(pair: &str) {  
    // format the ws_url  
  let ws_url: String = format!("{}/ws/{}@depth20", WS_BASE_URL, pair);  
  // build the ws url connection request add tls support for wss  
  #[cfg(not(any(feature = "tokio-tls", feature = "tokio-runtime")))]  
  let url = url::Url::parse(&ws_url).unwrap();  
  // connect to the ws  
  let (mut ws_stream, _) = connect_async(url.clone()).await.unwrap();  
  // while connected  
  loop {  
        // wait for messages  
  let msg = ws_stream  
  .next()  
            .await  
  .ok_or_else(|| "didn't receive anything").unwrap().unwrap();  
  
  match msg{  
            Message::Text(msgtxt)=> {  
                println!("Message {:?}", msg);
  } ,  
  Message::Ping(_msg) => continue,  
  Message::Binary(_msg)=> continue,  
  Message::Pong(_msg)=> continue,  
  Message::Close(msg)=> {println!("Close {:?}", msg); // re-open connection here  
  let (mut ws_stream, _) = connect_async(url.clone()).await.unwrap();  
  },  
  };  
  }  
}  
#[tokio::main]  
async fn main(){  
    let markets = vec!["btcusdt", "ethusdt", "etcusdt", "bchusdt","bnbusdt", "eosusdt","xrpusdt" ,"ltcusdt","busdusdt","zecusdt","adausdt", "btcpax","atomusdt", "trxusdt", "xlmusdt", "bttusdt", "vetusdt", "tusdusdt"];  
  let mut children = vec![];  
  for pair in markets{  
        children.push(  
            tokio::spawn( subscribe_to_market(pair))  
//subscribe_to_market(pair)  
  );  
  }  
    let all_futures = futures::future::join_all(children);  
  all_futures.await;  
}
```

**Comment by sdroege** [comment]
Async code will generally be slower in the small scale than sync code. There's a lot more book-keeping that has to be done compared to simply blocking a thread.

Async code starts to become better performance-wise once you have *a lot* of operations in parallel and running a whole OS thread for each of them would consume too many resources.

Async code also has the advantage of easier to read and maintain code since the async/await syntax was introduced.

Apart from that your code example does not seem to do much at all, I'd expect any performance differences here to be irrelevantly small unless something's going really wrong. What numbers do you measure and how?

The comparison with Python is not too useful in this regard because Python is effectively single-threaded by the use of the global interpreter lock. By running async code in Python you can do lots of operations in parallel while actually blocking would potentially block everything.

That said, I'm sure there might be some parts in this crate that can be optimized further. I'd recommend doing some profiling to find the bottlenecks if this is a concern for you.

**Comment by araa47** [comment]
Ive tried recently scaling this up to 714 connections with 714 threads vs 714 tokio::spawn() tasks to try to make this more 'large' scale.

The numbers I measured are of my mac using Activity Monitor.

*Threaded* 
Cpu Usage: 4-6% 
Threads: 717

*Async*
Cpu Usage: 5-7%
Threads: 5

 

It still seems to have a similar results. I guess my testing methodology may not be sound since I assumed that in the threaded version these connections are mostly just waiting for a websocket message to be received, so I was thinking that the async implementation would run faster. 

What would be a much better test for proving this  ?

**Comment by Patryk27** [comment]
~700 is still a pretty small number - try spawning 10k connections simultaneously (if you even manage to create 10k threads on your computer) :-)

**Comment by sdroege** [comment]
In addition to what @Patryk27 said, CPU usage is not the only thing you want to measure really. Those 717 threads are going to use up a lot of OS resources compared to 5 threads :)

**Comment by araa47** [comment]
Thanks for the help. After scaling I started to see differences at 2856 websocket connections. If i try to double that, the threads fail with the following error  

```
Number of markets 5712
thread 'main' panicked at 'failed to spawn thread: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

at **2856** ws connections it seems like the async implementation seems to be running at half the cpu usage and only consuming 4 threads      :-)

*Threaded*
Cpu Usage: 20-35
Threads: 2858

*Async*
Cpu Usage: 10-20%
Threads: 4

**Comment by sdroege** [comment]
Checking with async-std or gio as another runtime might also be interesting here. The performance is going to depend on the runtime too.

**Comment by araa47** [comment]
Will have a shot at this, and come back with some performance results

**Comment by najamelan** [comment]
@araa47 what have you found out? You might want to have a look at the memory usage, there will be a real difference there. You can [reduce the stack size](https://doc.rust-lang.org/std/thread/#stack-size) of threads to make them lighter though. You can also change the max number of threads on your system, eg. [for linux](https://stackoverflow.com/questions/5635362/max-thread-per-process-in-linux).
