### ISSUE TITLE
[Question]  Cancellation of read from websocket stream before completion

### ISSUE THREAD

**Issue by hn-sl** [sdroege/async-tungstenite#81]
```rust
use std::time::Duration;
use async_tungstenite::tokio::connect_async;
use futures::StreamExt;
use tokio::time::timeout;

#[tokio::main]
async fn main() {
    let (ws_stream, _) = connect_async("test").await.unwrap();
    let (_write, mut read) = ws_stream.split();

    // First read. Safe ?? 
    if let Err(_) = timeout(Duration::from_millis(10), read.next()).await {
        println!("did not receive message within 10 ms");
    }

    // Second read
    let message = read.next().await;
}

```

Let's say the first ```read.next()``` read few bytes but not whole message within 10 ms.  What happen to the bytes that is read? Are they discarded or kept in buffer for next read?  So if remaining bytes of message is arrived later, does the second ```read.next()``` read the message properly? I wonder whether cancellation of read before completion can cause any problem for next read.

**Comment by sdroege** [comment]
In theory the you should not lose any message here and the socket should be usable again afterwards and you would just get the next message. If that's not the case then this should be fixed.

Can you provide a testcase that shows that this is currently broken?

**Comment by hn-sl** [comment]
Thanks. I also check from source code that there should be no any issue.  I will make a testcase soon.
