### ISSUE TITLE
async_tungstenite::tokio::ConnectStream doesn't implement Debug when feature "tokio-native-tls" is enabled.

### ISSUE THREAD

**Issue by hn-sl** [sdroege/async-tungstenite#82]
Cargo.toml
```
[dependencies]
async-tungstenite = { version = "0.13.0", features = ["tokio-runtime", "tokio-native-tls"] }
```

main.rs
``` rust
use async_tungstenite::tokio::ConnectStream;

#[derive(Debug)]
struct Foo(ConnectStream);

fn main() {
    println!("Hello, world!");
}
```

This produce compile error :    error[E0277]: `async_tungstenite::stream::Stream<TokioAdapter<tokio::net::tcp::stream::TcpStream>, TokioAdapter<tokio_native_tls::TlsStream<tokio::net::tcp::stream::TcpStream>>>` doesn't implement `Debug`

I hope this type implements debug.

**Comment by sdroege** [comment]
It might be sufficient to `#[derive(Debug)]` in https://github.com/sdroege/async-tungstenite/blob/1170f4e080ba97a48bae285b07d5f022e5b1292d/src/stream.rs#L12

It might also be necessary to implement `Debug` for other types then though, including `tokio_native_tls::TlsStream`.

Do you want to give it a try?

**Comment by hn-sl** [comment]
I just confirmed that adding ```#[derive(Debug)]``` to the Stream in your comment is sufficient.

**Comment by sdroege** [comment]
Great, do you want to submit a PR for that?

**Comment by hn-sl** [comment]
Sure I just submitted it.

**Comment by sdroege** [comment]
Thanks :)
