### ISSUE TITLE
max connect just 50 onely

### ISSUE THREAD

**Issue by xlpxxx** [sdroege/async-tungstenite#86]
```
url = "2.2.1"
http = "0.2.3"
libc = "0.2.88"
regex = "1"
lazy_static = "1.4.0"
futures-util = "0.3.13"
tokio = { version = "1.3.0", features = ["full"] }
async-tungstenite ={ version = "0.13.0", features = ["tokio-native-tls"] }


tokio-native-tls = { version = "^0.3.0", optional = true}
```
[code](https://gitee.com/wlp_sixsixsix/websocket-epl/tree/master/rust%E5%B0%81%E8%A3%85%E7%89%88/rs-ws)

When the number of connections exceeds 50, only disconnect the socket that is already connected can you connect again

**Comment by xlpxxx** [comment]
emmmmm, server limit, did not notice this problem

**Comment by sdroege** [comment]
Yeah these kind of things can sometimes be confusing :)
